# Generated by Django 4.2.7 on 2024-01-08 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_product_author_alter_product_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
