# Generated by Django 4.2.7 on 2024-01-10 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_product_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'permissions': [('edit_published', 'Can publish posts')], 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
    ]
